sudo: true
language: node_js
node_js:
  - 12

cache: yarn

install:
  - yarn

script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master

after_deploy:
  - rm -rf !(doc)
  - mv doc/* ./
  - rm -r doc
  - rm -r .travis.yml
  - rm -r .gitignore
